services:
  # Next.js Web
  textbee-web:
    container_name: textbee-web
    # image: ghcr.io/vernu/textbee/web:latest
    build:
      context: ./web
      dockerfile: Dockerfile
    restart: always
    ports:
      - "${WEB_PORT:-3000}:3000"
    env_file:
      - ./web/.env
    environment:
      - PORT=3000
      - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL:-http://localhost:3001/api/v1}
    networks:
      - textbee-network

networks:
  textbee-network:
    driver: bridge
